# This workflow builds the aws-opentelemetry-js-distro JavaScript files, uploads to staging S3 bucket, and builds the project docker image that is pushed to a staging ECR repository
name: NodeJS Instrumentation Main Build
on:
  push:
    branches:
      - main
      - "release/v*"
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1
  STAGING_ECR_REGISTRY: 637423224110.dkr.ecr.us-east-1.amazonaws.com
  STAGING_ECR_REPOSITORY: aws-observability/adot-autoinstrumentation-node-staging
  STAGING_S3_BUCKET: ${{ secrets.STAGING_BUCKET_NAME }}

concurrency:
  group: node-instrumentation-main-build
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  application-signals-e2e-test:
    name: "Application Signals E2E Test"
    uses: ./.github/workflows/application-signals-e2e-test.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read